import React, { useState } from 'react';
import { Copy, Check, AlertTriangle, ArrowLeft, ActivitySquare, CheckCircle2 } from 'lucide-react';

const ResultsView = ({ data, onReset }) => {
  const [copiedSection, setCopiedSection] = useState(null);

  const handleCopy = (text, sectionName) => {
    if (!text) return;
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionName);
    setTimeout(() => setCopiedSection(null), 2000);
  };

  const handleCopyAll = () => {
    const fullText = `
ASSESSMENT:
${data.assessment}

DIAGNOSIS:
${data.diagnosis}

INTERVENTION:
${data.intervention}

MONITORING & EVALUATION:
${data.monitoring_evaluation}
    `.trim();
    
    handleCopy(fullText, 'all');
  };

  const SectionCard = ({ title, content, id }) => (
    <div className="bg-white rounded-2xl shadow-sm hover:shadow-md border border-slate-100 p-6 relative group transition-all duration-300">
      <div className="flex justify-between items-center mb-4">
        <h3 className="text-sm font-bold tracking-widest text-emerald-800 font-heading uppercase flex items-center">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 mr-2"></span>
            {title}
        </h3>
        <button
          onClick={() => handleCopy(content, id)}
          className="text-slate-400 hover:text-emerald-600 hover:bg-emerald-50 rounded-lg p-2 transition-all duration-200 flex items-center"
          title={`Copy ${title}`}
        >
          {copiedSection === id ? (
            <Check size={18} className="text-emerald-500 scale-110 transition-transform" />
          ) : (
            <Copy size={18} className="transition-transform group-hover:scale-110" />
          )}
        </button>
      </div>
      <div className="text-slate-700 whitespace-pre-wrap leading-relaxed font-medium">
        {content || <span className="text-slate-400 italic">No content extracted.</span>}
      </div>
    </div>
  );

  return (
    <div className="w-full mx-auto p-4 sm:p-6 lg:p-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      
      {/* Top Navigation / Actions */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-8 pb-6 border-b border-slate-200/60">
        <button 
          onClick={onReset}
          className="flex items-center text-slate-500 hover:text-slate-800 font-semibold transition-colors group mb-4 sm:mb-0 bg-white px-4 py-2 rounded-xl shadow-sm border border-slate-100 hover:shadow-md"
        >
          <ArrowLeft size={18} className="mr-2 group-hover:-translate-x-1 transition-transform" />
          Back to Upload
        </button>
        <button
          onClick={handleCopyAll}
          className={`flex items-center px-6 py-2.5 font-bold rounded-xl transition-all duration-300 shadow-sm border ${
            copiedSection === 'all' 
              ? 'bg-emerald-100 text-emerald-700 border-emerald-200' 
              : 'bg-white text-slate-700 border-slate-200 hover:border-emerald-300 hover:text-emerald-700 hover:shadow-md'
          }`}
        >
          {copiedSection === 'all' ? (
            <><CheckCircle2 size={18} className="mr-2 text-emerald-600" /> Copied Full Draft</>
          ) : (
            <><Copy size={18} className="mr-2" /> Copy Full Draft</>
          )}
        </button>
      </div>

      {/* Main Draft Label */}
      <div className="bg-gradient-to-r from-rose-50 to-pink-50 border border-rose-200/60 p-5 rounded-2xl mb-8 shadow-sm relative overflow-hidden group">
        <div className="absolute top-0 left-0 w-1 h-full bg-gradient-to-b from-rose-400 to-pink-400" />
        <div className="flex items-start sm:items-center text-left">
          <div className="bg-rose-100 max-sm:p-2 sm:p-2.5 rounded-xl mr-4 shrink-0 mt-0.5 sm:mt-0 transition-transform group-hover:scale-110 duration-300">
             <AlertTriangle className="text-rose-600" size={24} />
          </div>
          <div>
            <h3 className="text-rose-900 font-bold font-heading tracking-wide uppercase text-sm mb-1">
              Draft Output — Clinician Review Required
            </h3>
            <p className="text-rose-700/90 text-sm font-medium leading-relaxed mb-0">
              This content was generated by AI and may contain errors. Review carefully before entering into Kickoff.
            </p>
          </div>
        </div>
      </div>

      {/* PHI Warning */}
      {data.phi_warning && (
        <div className="bg-amber-50 border border-amber-200/60 p-5 rounded-2xl mb-8 shadow-sm flex items-start animate-in slide-in-from-top-4">
          <div className="bg-amber-100/50 p-2.5 rounded-xl mr-4 shrink-0 transition-transform hover:scale-110 duration-300">
             <AlertTriangle className="text-amber-500" size={24} />
          </div>
          <div>
            <h4 className="text-amber-900 font-bold font-heading text-sm uppercase tracking-wide mb-1">Potential PHI Detected</h4>
            <p className="text-amber-700/90 text-sm font-medium leading-relaxed">
              The system detected patterns resembling Personally Identifiable Information (like phone numbers or SSNs) in your notes. Please ensure you strictly upload de-identified notes.
            </p>
          </div>
        </div>
      )}

      {/* Attention Required / Validation Flags */}
      {data.needs_review && (
        <div className="bg-gradient-to-br from-indigo-50 to-blue-50 border border-indigo-100 p-6 rounded-2xl mb-10 shadow-sm relative overflow-hidden">
          <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/5 rounded-bl-full pointer-events-none" />
          
          <h4 className="text-indigo-900 font-bold font-heading text-lg mb-5 flex items-center">
             <div className="bg-indigo-100 p-2 rounded-lg mr-3">
                 <ActivitySquare size={20} className="text-indigo-600" />
             </div>
             Attention Required
          </h4>
          
          <div className="space-y-5">
              {data.missing_items && data.missing_items.length > 0 && (
                 <div className="bg-white/60 p-4 rounded-xl border border-indigo-100/50">
                   <strong className="text-indigo-900 font-semibold text-sm mb-2 block flex items-center">
                     <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 mr-2"></span> Missing Information:
                   </strong>
                   <ul className="list-disc pl-6 text-indigo-700/90 font-medium text-sm space-y-1.5">
                     {data.missing_items.map((item, idx) => <li key={idx}>{item}</li>)}
                   </ul>
                 </div>
              )}

              {data.review_notes && data.review_notes.length > 0 && (
                 <div className="bg-white/60 p-4 rounded-xl border border-indigo-100/50">
                   <strong className="text-indigo-900 font-semibold text-sm mb-2 block flex items-center">
                      <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 mr-2"></span> Review Notes:
                   </strong>
                   <ul className="list-disc pl-6 text-indigo-700/90 font-medium text-sm space-y-1.5">
                     {data.review_notes.map((note, idx) => <li key={idx}>{note}</li>)}
                   </ul>
                 </div>
              )}
              
              {data.follow_up_suggestions && data.follow_up_suggestions.length > 0 && (
                 <div className="bg-white/60 p-4 rounded-xl border border-indigo-100/50">
                   <strong className="text-indigo-900 font-semibold text-sm mb-2 block flex items-center">
                       <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 mr-2"></span> Follow-up Suggestions:
                   </strong>
                   <ul className="list-disc pl-6 text-indigo-700/90 font-medium text-sm space-y-1.5">
                     {data.follow_up_suggestions.map((sug, idx) => <li key={idx}>{sug}</li>)}
                   </ul>
                 </div>
              )}
          </div>
        </div>
      )}

      {/* Draft Cards */}
      <div className="space-y-6">
        <SectionCard title="Assessment" id="assessment" content={data.assessment} />
        <SectionCard title="Diagnosis" id="diagnosis" content={data.diagnosis} />
        <SectionCard title="Intervention" id="intervention" content={data.intervention} />
        <SectionCard title="Monitoring & Evaluation" id="monitoring_evaluation" content={data.monitoring_evaluation} />
      </div>

    </div>
  );
};

export default ResultsView;
